/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/bitshopb.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bitshop({ position, color, selected }) {
  const { nodes, materials } = useGLTF("models/bitshopb.glb");
  return (
    <group position={[position.x, 0.6, position.y]} scale={[0.3, 0.3, 0.3]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Black_bitshop.geometry}
        material={materials["Material.001"]}
      >
        {" "}
        <meshStandardMaterial
          roughness={0.1}
          metalness={0.7}
          color={selected ? "green" : color === "w" ? "white" : "black"}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("models/bitshopb.glb");
